//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace SCLIP.Act.Configuration {
=======
namespace $safeprojectname$.Act.Configuration {
>>>>>>> b27f45d06842ef02074930127f0fc5e0a8f3b40b
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Keys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Keys defaultInstance = ((Keys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Keys())));
        
        public static Keys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login {
            get {
                return ((string)(this["Login"]));
            }
            set {
                this["Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Encrypt {
            get {
                return ((string)(this["Encrypt"]));
            }
            set {
                this["Encrypt"] = value;
            }
        }
    }
}
